server:
  port: 8009
spring:

  application:
    name: sis_gis-backend

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/bddsisgis?useSSL=false
    username: root
    password: 12345678
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop